using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum StringType
{
    NA,
    Title_Quit,
    Title_Save,
    Title_Test,
    Title_Generation,
    Button_Delete,
    Button_Load,
    Button_Export,
    Button_Save,
    Button_Generate,
    Button_Regenerate,
    Button_Revert,
    Button_Clear,
    Tooltip_Export_Disabled_Content,
    Tooltip_Save_Disabled_Content,
    Tooltip_Export_Disabled_Header,
    Tooltip_Save_Disabled_Header,
    Description_Generator_CellularA,
    Description_Generator_Copy,
    Description_Generator_DLA,
    Description_Generator_EntranceExit,
    Description_Generator_Initial,
    Description_Generator_Labyrinth,
    Description_Generator_Noise,
    Description_Generator_Oval,
    Description_Generator_Perlin,
    Description_Generator_RandomWalk,
    Description_Generator_RoomConnection,
    Description_Generator_RoomFill,
    Description_Generator_UniversalMask,
    Description_Generator_Development,
    Description_Test_Continuity,
    Description_Test_XOfY,
    Description_Test_ExitReachable,
    Tooltip_Layer_Button_Ground,
    Tooltip_Layer_Button_Wall,
    Tooltip_Layer_Button_Object,
    Tooltip_Layer_Button_Debug,
    Tooltip_Toggle_Button_Image,
    Tooltip_Toggle_Button_Size,
    Tooltip_Toggle_Button_TestSize,
    Tooltip_Toggle_Button_PassFail,
    Tooltip_Layer_Button_Number,
    Tooltip_Toggle_Button_Mask,
    Description_Generator_UpscaledNoise,
    Description_Generator_DistanceFill
}